% Multi-patch parametrization of a quadrilateralized spherical cube
function mdl = mdl_quad_sphere(scale)
    nrb = nrb_quad_sphere;
    
    mdl.nrb = {nrbtform(nrb, vecscale(scale) * vecroty(-pi / 2)),...
               nrbtform(nrb, vecscale(scale) * vecroty(pi / 2)),...
               nrbtform(nrb, vecscale(scale) * vecrotx(pi / 2)),...
               nrbtform(nrb, vecscale(scale) * vecrotx(-pi / 2)),...
               nrbtform(nrb, vecscale(scale) * vecroty(pi)),...
               nrbtform(nrb, vecscale(scale))};
    
    mdl.fcs = {[1, 1; 5, 2],...
               [6, 1; 1, 2],...
               [2, 1; 6, 2],...
               [5, 1; 2, 2],...
               [3, 3; 5, 3],...
               [6, 3; 3, 4],...
               [4, 3; 6, 4],...
               [5, 4; 4, 4],...
               [1, 4; 4, 1],...
               [3, 1; 1, 3],...
               [2, 3; 3, 2],...
               [4, 2; 2, 4]};
    
    mdl.flp = false(1, numel(mdl.fcs));
    mdl.flp([5, 8, 9, 11]) = true;
    
    mdl.dbd = [];
end
